registerLab({
  id: "52-agentic-incident-response",
  order: 52,
  title: "Autonomous containment from untrusted incident data",
  mysteryTitle: "Automated containment",
  difficulty: "expert",
  category: "auth",
  env: "node",
  mode: "static",
  track: "architecture-review",
  architecture: {
    context: "An AI incident-response agent summarizes alerts and can block players, pause economy features and roll back deployments to reduce response time.",
    assets: ["Production availability", "Player account access", "Deployment control", "Forensic evidence"],
    constraints: ["Alerts contain attacker-controlled log text", "Responders are on call", "Some containment must happen in minutes", "False positives affect millions of players"],
    questions: ["Which inputs can an attacker influence?", "Which actions are reversible and bounded?", "Where must human approval or independent evidence be required?"]
  },
  filename: "design/agentic-ir.txt",
  description: "An incident agent consumes attacker-influenced logs and automatically executes broad containment tools based on model confidence.",
  code: [
    "Logs + tickets + alerts -> RAG index -> IncidentAgent context",
    "IncidentAgent: classify incident and assign confidence 0..1",
    "If confidence >= 0.85: execute proposed tools without approval",
    "Tools: blockAnyPlayer, pauseGlobalEconomy, rollbackAnyDeployment, deleteQueue",
    "Tool arguments are generated by the model from alert text",
    "Agent service account has production-admin in every region",
    "After execution: send summary to the on-call responder"
  ].join("\n"),
  vulnerableLines: [1, 3, 4, 5, 6],
  hints: [
    "Logs and tickets can contain attacker-authored strings, including instructions aimed at the model.",
    "Model confidence is not an authorization or change-management control.",
    "Compare reversible account quarantine with global economy pause, deployment rollback and evidence deletion.",
    "Use two-phase plan/execute, independent policy checks, scoped credentials and approval based on impact."
  ],
  vulnerabilityType: "Indirect prompt injection and excessive agency in incident containment",
  explanation:
    "<h4>Design failure</h4><p>Attacker-influenced evidence enters agent context while the same agent holds global destructive capabilities. A self-reported confidence threshold turns probabilistic output into authorization, and notification occurs only after impact.</p>" +
    "<h4>Proposed design</h4><p>Separate investigation from execution. The agent produces a cited plan; deterministic policy classifies each action by scope, reversibility and evidence requirements. Low-impact temporary quarantine may be automated with strict bounds, while global pause, rollback or deletion requires explicit human approval and stronger independent signals.</p>" +
    "<h4>Capability controls</h4><p>Issue short-lived credentials for one incident, environment and action. Remove evidence-deletion tools, cap batch size, support dry-run, maintain a kill switch and store immutable before/after audit outside the agent's authority.</p>" +
    "<h4>Validation</h4><p>Inject instructions into logs, poison retrieved runbooks, spoof confidence, target another region, repeat actions, simulate approval outage and verify safe degradation plus rapid human override.</p>"
});
